# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Excel_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Excel_ui(object):
    def setupUi(self, Excel_ui):
        Excel_ui.setObjectName("Excel_ui")
        Excel_ui.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Excel_ui.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(Excel_ui)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 291, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.FileTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.FileTextEdit.setObjectName("FileTextEdit")
        self.horizontalLayout_2.addWidget(self.FileTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.SaveTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.SaveTextEdit.setObjectName("SaveTextEdit")
        self.horizontalLayout_4.addWidget(self.SaveTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.ColumnSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ColumnSpinBox.setMinimum(1)
        self.ColumnSpinBox.setProperty("value", 3)
        self.ColumnSpinBox.setObjectName("ColumnSpinBox")
        self.horizontalLayout_6.addWidget(self.ColumnSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.ThreadsSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ThreadsSpinBox.setMinimum(1)
        self.ThreadsSpinBox.setMaximum(16)
        self.ThreadsSpinBox.setProperty("value", 6)
        self.ThreadsSpinBox.setObjectName("ThreadsSpinBox")
        self.horizontalLayout_7.addWidget(self.ThreadsSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(Excel_ui)
        self.line.setGeometry(QtCore.QRect(300, 10, 21, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.StartPushButton = QtWidgets.QPushButton(Excel_ui)
        self.StartPushButton.setGeometry(QtCore.QRect(10, 510, 291, 51))
        self.StartPushButton.setObjectName("StartPushButton")
        self.progressBar = QtWidgets.QProgressBar(Excel_ui)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(17, 570, 281, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.TableWidget = QtWidgets.QTableWidget(Excel_ui)
        self.TableWidget.setGeometry(QtCore.QRect(315, 11, 481, 581))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)

        self.retranslateUi(Excel_ui)
        QtCore.QMetaObject.connectSlotsByName(Excel_ui)

    def retranslateUi(self, Excel_ui):
        _translate = QtCore.QCoreApplication.translate
        Excel_ui.setWindowTitle(_translate("Excel_ui", "Excel批量下载"))
        self.label.setText(_translate("Excel_ui", "文件地址："))
        self.FileTextEdit.setPlaceholderText(_translate("Excel_ui", "请输入xls/xlsx文件地址，也可将文件拖拽到本窗口。"))
        self.label_3.setText(_translate("Excel_ui", "保存地址："))
        self.SaveTextEdit.setPlaceholderText(_translate("Excel_ui", "请输入保存文件夹地址，也可将文件夹拖拽到本窗口。"))
        self.label_4.setText(_translate("Excel_ui", "命名列号："))
        self.label_5.setText(_translate("Excel_ui", "下载线程："))
        self.checkBox.setText(_translate("Excel_ui", "为每个对象新建文件夹"))
        self.StartPushButton.setText(_translate("Excel_ui", "开始下载"))


